### PR TITLE
[#8] Implement support to ship logs to listener-eu

### PR DESCRIPTION
**Pull request by dgreda**

### CODE REVIEW

**Comment by Chrico** [comment]
Howdy @dgreda .

Thanks a lot for your pull. could you pls provide some more information about this `-eu`-endpoint? Cannot find any information to this in officali documentation. Are there even more endpoints?

*Edit:* Maybe this is a hint to it: https://docs.logz.io/user-guide/log-shipping/listener-ip-addresses.html

**Comment by dgreda** [comment]
Hi @Chrico, exactly, I referred to that link in the issue which I created here: https://github.com/inpsyde/logzio-monolog/issues/8

**Comment by dgreda** [comment]
@Chrico do you think that we could get it merged and tagged soon, so that we can successfully use your library in our project to ship logs to non-default logz.io listener?

**Comment by Chrico** [comment]
Ok, thanks for your feedback. Are there any differences for those 2 hosts or are those just different located servers which are sending to the same backend at the end?

I would like to see some smaller changes here:

1. Introduce class constants for both
2. use `$host` with `.logz.io` instead of just `$listenerName`

```php

class LogzIoHandler
{
	
	const HOST_EU = 'listener-eu.logz.io';
	const HOST_US = 'listener.logz.io';

	public function __construct(
        string $token,
        string $type = 'http-bulk',
        bool $ssl = true,
        int $level = Logger::DEBUG,
        bool $bubble = true,
        string $host = self::HOST_US
    ) {
        $this->token = $token;
        $this->type = $type;

        $this->endpoint = $ssl ? 'https://' . $host . ':8071/' : 'http://' . $host . ':8070/';
        $this->endpoint .= '?'.http_build_query(
            [
                'token' => $this->token,
                'type' => $this->type,
            ]
        );
        parent::__construct($level, $bubble);
    }
}
```

-----

**Edit:** it seems that several handlers _in_ Monolog are handling this differently:

- LogEntries uses `$host` https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/LogEntriesHandler.php#L41
- InsightOpsHandler uses `$region` https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/InsightOpsHandler.php#L45

I'd like to stick to `$host`, because it could be possible in future that there are more hosts available for a specific region.

**Comment by dgreda** [comment]
@Chrico I pushed changes. To browse the logs pushed to listener in EU we still use normal backend of logz.io so I assume it's just another region for lower latency within EU. I guess it also has to be configured per account, since for me pushing directly to `listener` didn't result in logs in our account.

**Comment by Chrico** [comment]
Good to know. Maybe this could also reduce a bit our response time, since most of our applications are located in EU. :)

**Comment by Chrico** [comment]
0.4 Release was done. :-)

**Comment by dgreda** [comment]
Great! Thanks for quick release :)

**Pull request merged**
