### PR TITLE
test PHP 7.3

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by OskarStark** [comment]
Will rebase after the merge of #6

**Comment by OskarStark** [comment]
This one is green and ready to merge.

Can you please create a new release after this merge?
Thank you

**Comment by bueltge** [comment]
@oskarstark BTW. In which context do you use the library, for the shop monitoring? Thx.

**Comment by OskarStark** [comment]
Hey @bueltge 

No for an internal tool, but the "performance" is quite bad :(
I think I need to switch back to filebeat again

**Comment by Chrico** [comment]
Have you tried out to bulk-send the logs to logz,io? @OskarStark

**Comment by OskarStark** [comment]
> Have you tried out to bulk-send the logs to logz,io? @OskarStark

I would say yes, at it is the default, right?

**Comment by Chrico** [comment]
Depends on how you're using it. Monolog, by default, does not send in bulk. So you have to use something like this:

```php
<?php declare(strict_types=1);

use Inpsyde\LogzIoMonolog\Handler\LogzIoHandler;
use Monolog\Handler\BufferHandler;
use Monolog\Logger;

$handler = new BufferHandler(new LogzIoHandler($token));

$logger = new Logger('name');
$logger->pushHandler($handler);
```

**Comment by OskarStark** [comment]
Ähm I used the symfony monolog settings.
Are you using it with symfony?

I thought it is default, because of:
```php
    public function __construct(
        string $token,
        string $type = 'http-bulk',
        bool $ssl = true,
        int $level = Logger::DEBUG,
        bool $bubble = true
    ) {
``

`http-bulk`

**Comment by Chrico** [comment]
Hehe no, Monolog does trigger `HandlerInterface::handle` on every `Logger::log`-call. The `$type` - which was wrongly documented (updated it) is for:


> Your log type - it helps classify the logs you send. This will be added as field called 'type' to all the JSON log you are sending in the body, overriding the value if it has this field. If missing we default to 'http-bulk'.

See also: https://app.logz.io/#/dashboard/data-sources/Bulk-HTTPS  (needs login).

You've to use the `BulkHandler` from Monolog to collect those records in memory and bulk send them via Multiline JSON via `LogzIoHandler`. You can configure this in Symfony via:

```
# app/config/config_{env}.yml
monolog:
    handlers:
        buffered:
            type:    buffer
            handler: logzio
        logzio:
                ....
```

**Comment by OskarStark** [comment]
is it possible to log to logz io AND to a file?

**Comment by OskarStark** [comment]
Can you merge this?

**Comment by Chrico** [comment]
Sure!

**Pull request merged**
