### PR TITLE
Add ext-curl to dependency list in composer.json

### LINKED ISSUE #1: Add `ext-curl` to list of dependencies
The constructor of LogzIoHandler throws an exception if the curl extension is not loaded. This could be handled on build time when `"ext-curl": "*"` would be added to the `require` section in `composer.json`

### PR DESCRIPTION
**Pull request by dnaber-de**
fixes #1

### CODE REVIEW

**Comment by Chrico** [comment]
If i add this, i'll have to remove this: https://github.com/inpsyde/logzio-monolog/blob/master/src/Handler/LogzIoHandler.php#L50  or not? :-) @dnaber-de

**Comment by dnaber-de** [comment]
Indeed, that's the idea. Failing at buildtime is IMO better than failing at runtime.

**Comment by Chrico** [comment]
Would you be so kind and update the code as well in this PR? :)

**Comment by dnaber-de** [comment]
IIRC I made this change in the Github GUI. :grin: So I'm not sure how to update this PR.

**Comment by Chrico** [comment]
You've created a new branch "issue-1-ext-curl" -> https://github.com/inpsyde/logzio-monolog/tree/issue-1-ext-curl , so i guess we can checkout this one and commit more stuff to it 😬

**Comment by dnaber-de** [comment]
Sure, I'll added it to my Todo list :)

**Comment by dnaber-de** [comment]
@Chrico the changes have been made you can merge this now. The errors from travis should be solved with PR #4 
Both PRs could be included in a release `0.3` (I already added a CHANGELOG.md)

**Pull request merged**
